(clear)
(set-strategy complexity)
(set-fact-duplication TRUE)
(load "./templates/carta.clp")
(load "./templates/juego.clp")
(load "./templates/hayMasCartasDeOtrosJugadores.clp")
(load "./templates/cambioConteoHiLo.clp")
(load "./templates/ronda.clp")
(load "./templates/mano.clp")
(load "./templates/nuevaCartaEnMano.clp")
(load "./templates/laBancaEstaJugando.clp")
(load "./rules/actualizarContadorHiLo.clp")
(load "./rules/cargarCartas.clp")
(load "./rules/nuevaRonda.clp")
(load "./rules/actualizarMano.clp")
(load "./hechosIniciales.clp")
(reset)
